-- ═══════════════════════════════════════════════════════
-- TASK NAME: LOINC-BRIDGE-SCHEMA
-- Phase: LOINC Unification · Sprint 0 (Foundation)
-- Run order: after naming-standards-schema.sql
-- Repeat safety: SAFE (drop+recreate table, view, function; idempotent seed)
-- Purpose: canonical LOINC/RSNA Radiology Playbook controlled vocabularies
--          (modality/region/focus/laterality/aggregation) with RadLex RIDs,
--          mirroring modules/data/loinc-bridge.js for server-side / RLS-safe use.
-- Source: LOINC 2.82 · LoincRsnaRadiologyPlaybook.csv
-- Attribution: LOINC® © Regenstrief Institute, Inc. · RadLex® © RSNA. https://loinc.org/license/
-- ═══════════════════════════════════════════════════════
do $$ begin raise notice '▶ TASK: LOINC-BRIDGE-SCHEMA — starting'; end $$;

create table if not exists public.loinc_axis (
  id          bigint generated always as identity primary key,
  axis        text not null check (axis in ('modality','modalitySub','region','focus','laterality','aggregation')),
  part_name   text not null,
  radlex_rid  text,
  preferred_name text,
  usage_count integer not null default 0,
  region_hint text,
  unique (axis, part_name)
);
comment on table public.loinc_axis is 'LOINC/RSNA Radiology Playbook canonical axis values (LOINC 2.82). LOINC(R) (c) Regenstrief; RadLex(R) (c) RSNA.';

-- idempotent seed
truncate public.loinc_axis restart identity;
insert into public.loinc_axis (axis, part_name, radlex_rid, preferred_name, usage_count, region_hint) values
('modality', 'XR', 'RID10345', 'projection radiography', 2505, null),
('modality', 'CT', 'RID10321', 'computed tomography', 1157, null),
('modality', 'MR', 'RID10312', 'Magnetic resonance imaging', 969, null),
('modality', 'RF', 'RID10361', 'Fluoroscopy', 800, null),
('modality', 'US', 'RID10326', 'Ultrasound', 645, null),
('modality', 'NM', 'RID10330', 'nuclear medicine imaging', 494, null),
('modality', '{Imaging modality}', 'RID10311', 'imaging modality', 245, null),
('modality', 'MG', 'RID10357', 'mammography', 191, null),
('modality', 'PT+CT', 'RID10341', 'Pet-ct', 26, null),
('modality', 'PT', 'RID10337', 'Positron emission tomography', 19, null),
('modality', 'NM.SPECT+CT', 'RID49583', 'SPECT-CT', 6, null),
('modality', 'DXA', 'RID10363', 'dual energy xray absorptiometry', 5, null),
('modalitySub', 'Angio', 'RID10371', 'ANGIOGRAPHY', 661, null),
('modalitySub', 'Portable', 'RID10383', 'portable', 168, null),
('modalitySub', 'Doppler', 'RID10375', 'Doppler', 141, null),
('modalitySub', 'SPECT', 'RID10334', 'single photon emission computed tomography', 113, null),
('modalitySub', 'Tomography', 'RID28840', 'tomography', 78, null),
('modalitySub', 'Stereotactic', 'RID50260', 'Stereotactic radiography', 18, null),
('modalitySub', 'tomosynthesis', 'RID10359', 'tomosynthesis', 15, null),
('modalitySub', 'Perfusion', 'RID10376', 'perfusion imaging', 14, null),
('modalitySub', 'FFD', 'RID10351', 'Digital radiography', 10, null),
('modalitySub', 'Video', 'RID45718', 'Videography', 8, null),
('modalitySub', 'Elastography', 'RID10932', 'Elastography', 5, null),
('modalitySub', 'stereoscopic', 'RID50131', 'Stereoscopy', 4, null),
('modalitySub', 'Functional', 'RID10317', 'Functional magnetic resonance imaging', 3, null),
('modalitySub', 'Spectral', 'RID50772', 'Spectral mammography', 3, null),
('modalitySub', 'Cone beam', 'RID50650', 'cone beam computed tomography', 3, null),
('modalitySub', 'Positron Emission', 'RID50771', 'Positron emission mammography (PEM)', 2, null),
('modalitySub', 'Slot radiography', 'RID50651', 'Slot radiography', 2, null),
('modalitySub', 'Spectroscopy', 'RID10377', 'Spectroscopy', 2, null),
('modalitySub', 'Scanogram', 'RID35773', 'scanogram', 2, null),
('modalitySub', 'Densitometry', 'RID28706', 'densitometry', 2, null),
('modalitySub', 'Tractography', 'RID12705', 'tractography', 1, null),
('modalitySub', 'A-scan', 'RID10903', 'A-scan', 1, null),
('region', 'Lower extremity', 'RID2638', 'Lower extremity', 1401, null),
('region', 'Abdomen', 'RID56', 'Abdomen', 1194, null),
('region', 'Upper extremity', 'RID1850', 'Upper extremity', 1180, null),
('region', 'Chest', 'RID1243', 'Thorax', 1154, null),
('region', 'Head', 'RID9080', 'head', 746, null),
('region', 'Pelvis', 'RID2507', 'Pelvis', 645, null),
('region', 'Neck', 'RID7488', 'neck', 411, null),
('region', 'XXX', 'RID6062', 'Body region', 362, null),
('region', 'Breast', 'RID28749', 'breast', 312, null),
('region', 'Extremity', 'RID13202', 'limb of body', 94, null),
('region', 'Whole Body', 'RID39569', 'whole body', 82, null),
('region', 'Umbilical artery', 'RID35962', 'umbilical artery', 2, null),
('region', 'Biliary system', 'RID28753', 'biliary system', 1, null),
('region', 'Spine', 'RID7741', 'Spine', 1, null),
('region', 'Umbilical vessels', 'RID50043', 'set of umbilical vessels', 1, null),
('region', 'Umbilical cord', 'RID34558', 'Umbilical Cord', 1, null),
('region', 'Cerebral artery middle', 'RID665', 'middle cerebral artery', 1, null),
('focus', 'Shoulder', 'RID1852', 'Shoulder girdle', 462, 'Upper extremity'),
('focus', 'Knee', 'RID2743', 'knee', 264, 'Lower extremity'),
('focus', 'Hip', 'RID2639', 'hip', 229, 'Lower extremity'),
('focus', 'Spine.lumbar', 'RID34573', 'Lumbar vertebral column', 206, 'Abdomen'),
('focus', 'Wrist', 'RID2177', 'Wrist', 192, 'Upper extremity'),
('focus', 'Heart', 'RID1385', 'heart', 190, 'Chest'),
('focus', 'Kidney', 'RID205', 'kidney', 170, 'Abdomen'),
('focus', 'Ankle', 'RID28545', 'Ankle', 149, 'Lower extremity'),
('focus', 'Spine.thoracic', 'RID28677', 'thoracic spine region', 147, 'Chest'),
('focus', 'Spine.cervical', 'RID34571', 'Cervical vertebral column', 130, 'Neck'),
('focus', 'Elbow', 'RID2010', 'elbow', 121, 'Upper extremity'),
('focus', 'Hand', 'RID2318', 'hand', 119, 'Upper extremity'),
('focus', 'Foot', 'RID28829', 'foot', 115, 'Lower extremity'),
('focus', 'Brain', 'RID6434', 'brain', 88, 'Head'),
('focus', 'Liver', 'RID58', 'liver', 85, 'Abdomen'),
('focus', 'Vein', 'RID1008', 'Vein', 75, 'XXX'),
('focus', 'Ribs', 'RID28591', 'set of ribs', 73, 'Chest'),
('focus', 'Sacrum', 'RID2509', 'Sacrum', 71, 'Pelvis'),
('focus', 'Orbit', 'RID28601', 'orbits', 66, 'Head'),
('focus', 'Clavicle', 'RID1854', 'clavicle', 59, 'Chest'),
('focus', 'Aorta.abdominal', 'RID905', 'Abdominal aorta', 55, 'Abdomen'),
('focus', 'Biliary ducts', 'RID45712', 'set of biliary ducts', 50, 'Abdomen'),
('focus', 'Lung', 'RID1301', 'Lung', 50, 'Chest'),
('focus', 'Sacroiliac joint', 'RID2577', 'Sacroiliac joint', 49, 'Pelvis'),
('focus', 'Aorta.thoracic', 'RID879', 'Thoracic aorta', 47, 'Abdomen'),
('focus', 'Femur', 'RID2662', 'femur', 46, 'Lower extremity'),
('focus', 'Tibia', 'RID2885', 'Tibia', 45, 'Lower extremity'),
('focus', 'Scapula', 'RID1860', 'Scapula', 45, 'Chest'),
('focus', 'Temporomandibular joint', 'RID9779', 'Temporomandibular joint', 45, 'Head'),
('focus', 'Calcaneus', 'RID2959', 'calcaneus', 44, 'Lower extremity'),
('focus', 'Bone', 'RID13197', 'bone organ', 43, 'XXX'),
('focus', 'Sinuses', 'RID28579', 'Paranasal sinuses', 42, 'Head'),
('focus', 'Radius', 'RID2109', 'Radius', 40, 'Upper extremity'),
('focus', 'Fibula', 'RID2871', 'Fibula', 40, 'Lower extremity'),
('focus', 'Thyroid gland', 'RID7578', 'thyroid gland', 39, 'Neck'),
('focus', 'Ulna', 'RID2119', 'Ulna', 39, 'Upper extremity'),
('focus', 'Humerus', 'RID1971', 'Humerus', 38, 'Upper extremity'),
('focus', 'Skull', 'RID9196', 'skull', 38, 'Head'),
('focus', 'Urinary bladder', 'RID237', 'Urinary bladder', 38, 'Pelvis'),
('focus', 'Lower extremity vessels', 'RID49928', 'Set of lower extremity vessels', 38, 'Lower extremity'),
('focus', 'Finger', 'RID2391', 'Finger', 37, 'Upper extremity'),
('focus', 'Spine', 'RID7741', 'Spine', 37, 'XXX'),
('focus', 'Thumb', 'RID2392', 'Thumb', 36, 'Upper extremity'),
('focus', 'Gallbladder', 'RID187', 'gallbladder', 35, 'Abdomen'),
('focus', 'Forearm', 'RID2107', 'forearm', 34, 'Upper extremity'),
('focus', 'Coccyx', 'RID2524', 'Coccyx', 32, 'Pelvis'),
('focus', 'Lower leg', 'RID2869', 'Leg', 32, 'Lower extremity'),
('focus', 'Upper extremity vessels', 'RID49863', 'Set of upper extremity vessels', 32, 'Upper extremity'),
('focus', 'Pancreas', 'RID170', 'Pancreas', 31, 'Abdomen'),
('focus', 'Upper arm', 'RID1968', 'Arm', 30, 'Upper extremity'),
('focus', 'Thigh', 'RID2660', 'Thigh', 29, 'Lower extremity'),
('focus', 'Ureter', 'RID229', 'Ureter', 28, 'Pelvis'),
('focus', 'Gastrointestinal tract.upper', 'RID29665', 'upper gastrointestinal tract', 28, 'Abdomen'),
('focus', 'Mandible', 'RID9082', 'Mandible', 27, 'Head'),
('focus', 'Toes', 'RID28757', 'set of toes', 26, 'Lower extremity'),
('focus', 'Finger.second', 'RID2394', 'Index finger', 26, 'Upper extremity'),
('focus', 'Acromioclavicular joint', 'RID1895', 'acromioclavicular joint', 26, 'Upper extremity'),
('focus', 'Mastoid', 'RID35754', 'Mastoid region', 26, 'Head'),
('focus', 'Carotid arteries', 'RID38751', 'Set of carotid arteries', 26, 'Neck'),
('focus', 'Sella turcica', 'RID9286', 'Sella turcica', 25, 'Head'),
('focus', 'Salivary gland', 'RID13421', 'Salivary gland', 25, 'Head'),
('focus', 'Renal Vessels', 'RID49537', 'Vasculature of kidney', 25, 'Abdomen'),
('focus', 'Internal auditory canal', 'RID9392', 'internal auditory canal', 25, 'Head'),
('focus', 'Spleen', 'RID86', 'Spleen', 25, 'Abdomen'),
('focus', 'Finger.third', 'RID2396', 'Long finger', 24, 'Upper extremity'),
('focus', 'Patella', 'RID2746', 'Patella', 24, 'Lower extremity'),
('focus', 'Pleural space', 'RID1363', 'Pleural space', 24, 'Chest'),
('focus', 'Sternoclavicular joint', 'RID1884', 'Sternoclavicular joint', 24, 'Chest'),
('focus', 'Finger.fifth', 'RID2400', 'Small finger', 23, 'Upper extremity'),
('focus', 'Head vessels', 'RID49926', 'Set of head vessels', 23, 'Head'),
('focus', 'Lower extremity veins', 'RID49969', 'Set of lower extremity veins', 23, 'Lower extremity'),
('focus', 'Iliac artery', 'RID39553', 'Set of iliac arteries', 23, 'Pelvis'),
('focus', 'Lower extremity joint', 'RID49861', 'joint of lower extremity', 23, 'Lower extremity'),
('focus', 'Finger.fourth', 'RID2398', 'Ring finger', 22, 'Upper extremity'),
('focus', 'Facial bones', 'RID28570', 'set of facial bones', 22, 'Head'),
('focus', 'Prostate', 'RID343', 'Prostate', 22, 'Pelvis'),
('focus', 'Scrotum', 'RID365', 'Scrotum', 21, 'Pelvis'),
('focus', 'Testicle', 'RID366', 'Testis', 21, 'Pelvis'),
('focus', 'Neck vessels', 'RID49931', 'Set of neck vessels', 20, 'Neck'),
('focus', 'Face', 'RID13284', 'face', 20, 'Head'),
('focus', 'Great toe', 'RID2993', 'Great toe', 19, 'Lower extremity'),
('focus', 'Vena cava.inferior', 'RID1178', 'Inferior vena cava', 19, 'Abdomen'),
('focus', 'Upper extremity joint', 'RID49862', 'joint of upper extremity', 19, 'Upper extremity'),
('focus', 'Colon', 'RID31011', 'Colon', 19, 'Pelvis'),
('focus', 'Pulmonary arteries', 'RID28586', 'Set of pulmonary arteries', 19, 'Chest'),
('focus', 'Temporal bone', 'RID9361', 'Temporal bone', 19, 'Head'),
('focus', 'Extremity vein', 'RID49981', 'Extremity vein', 18, 'Extremity'),
('focus', 'Aortic arch', 'RID581', 'aortic arch', 18, 'Chest'),
('focus', 'Small bowel', 'RID132', 'Small intestine', 18, 'Abdomen'),
('focus', 'Abdominal vessels', 'RID49921', 'Set of abdominal vessels', 18, 'Abdomen'),
('focus', 'Brachial plexus', 'RID7202', 'Brachial plexus', 18, 'Chest'),
('focus', 'Toe.third', 'RID2997', 'Third toe', 17, 'Lower extremity'),
('focus', 'Toe.fourth', 'RID2998', 'Fourth toe', 17, 'Lower extremity'),
('focus', 'Toe.fifth', 'RID2999', 'Fifth toe', 17, 'Lower extremity'),
('focus', 'Toe.second', 'RID2996', 'Second toe', 17, 'Lower extremity'),
('focus', 'Axilla', 'RID2470', 'axilla', 17, 'Chest'),
('focus', 'Vessel', 'RID4', 'Blood vessel', 17, 'XXX'),
('focus', 'Femoral artery', 'RID38761', 'Femoral artery', 17, 'Lower extremity'),
('focus', 'Bone marrow', 'RID38594', 'bone marrow', 17, 'XXX'),
('focus', 'Sternum', 'RID2473', 'Sternum', 16, 'Chest'),
('focus', 'Stomach', 'RID114', 'stomach', 16, 'Abdomen'),
('focus', 'Retroperitoneum', 'RID431', 'RETROPERITONEUM', 16, 'Abdomen'),
('focus', 'Artery', 'RID478', 'artery', 16, 'XXX'),
('focus', 'Joint', 'RID6122', 'Joint', 16, 'XXX'),
('focus', 'Pelvis vessels', 'RID49933', 'Set of pelvis vessels', 16, 'Pelvis'),
('focus', 'Lower extremity artery', 'RID49975', 'Lower extremity artery', 15, 'Lower extremity'),
('focus', 'Upper extremity veins', 'RID49944', 'Set of upper extremity veins', 15, 'Upper extremity'),
('focus', 'Gastrointestinal tract', 'RID94', 'gastrointestinal tract', 14, 'Pelvis'),
('focus', 'Esophagus', 'RID95', 'Esophagus', 14, 'Chest'),
('focus', 'Breast duct', 'RID49972', 'lactiferous duct', 14, 'Breast'),
('focus', 'Lower extremity vein', 'RID49982', 'Lower extremity vein', 14, 'Lower extremity'),
('focus', 'Maxillofacial region', 'RID35812', 'maxillofacial region', 14, 'Head'),
('focus', 'Extremity veins', 'RID49964', 'Set of extremity veins', 14, 'Extremity'),
('focus', 'Lymph node', 'RID13296', 'Lymph node', 14, 'XXX'),
('focus', 'Adrenal gland', 'RID88', 'adrenal gland', 14, 'Abdomen'),
('focus', 'Parotid gland', 'RID28744', 'Parotid gland', 14, 'Neck'),
('focus', 'Chest vessels', 'RID49962', 'Set of chest vessels', 13, 'Chest'),
('focus', 'Posterior fossa', 'RID35735', 'Posterior cranial fossa', 13, 'Head'),
('focus', 'Pituitary', 'RID38674', 'Pituitary gland', 13, 'Head'),
('focus', 'Pancreatic duct', 'RID176', 'pancreatic duct', 13, 'Abdomen'),
('focus', 'Muscle', 'RID13196', 'muscle organ', 13, 'XXX'),
('focus', 'Vertebral artery', 'RID774', 'vertebral artery', 13, 'Neck'),
('focus', 'Midfoot', 'RID2946', 'Midfoot', 13, 'Lower extremity'),
('focus', 'Zygomatic arch', 'RID28599', 'zygomatic arch', 12, 'Head'),
('focus', 'Urethra', 'RID34890', 'Urethra', 12, 'Pelvis'),
('focus', 'Popliteal artery', 'RID962', 'Popliteal artery', 12, 'Lower extremity'),
('focus', 'Coronary arteries', 'RID28727', 'Set of coronary arteries', 12, 'Chest'),
('focus', 'Upper extremity artery', 'RID49976', 'Upper extremity artery', 12, 'Upper extremity'),
('focus', 'Peritoneum', 'RID410', 'peritoneum', 11, 'Abdomen'),
('focus', 'Extremity vessels', 'RID49923', 'Set of extremity vessels', 11, 'Extremity'),
('focus', 'Vena cava.superior', 'RID1010', 'Superior vena cava', 11, 'Chest'),
('focus', 'Larynx', 'RID7589', 'larynx', 11, 'Neck'),
('focus', 'Uterus', 'RID302', 'Uterus', 11, 'Pelvis'),
('focus', 'Rectum', 'RID163', 'Rectum', 11, 'Pelvis'),
('focus', 'Portal vein', 'RID1208', 'Portal vein', 11, 'Abdomen'),
('focus', 'Ovary', 'RID290', 'Ovary', 11, 'Pelvis'),
('focus', 'Spine facet joint', 'RID7901', 'Facet joint of spine', 10, 'XXX'),
('focus', 'Vessels', 'RID39545', 'Set of blood vessels', 10, 'XXX'),
('focus', 'Renal vein', 'RID1184', 'Renal vein', 10, 'Abdomen'),
('focus', 'Carotid artery', 'RID584', 'Common carotid artery', 10, 'Head'),
('focus', 'Mediastinum', 'RID1384', 'Mediastinum', 10, 'Chest'),
('focus', 'Soft tissue', 'RID35730', 'Portion of soft tissue', 10, 'XXX'),
('focus', 'Pleura', 'RID1362', 'Pleura', 10, 'Chest'),
('focus', 'Hindfoot', 'RID2945', 'Hindfoot', 10, 'Lower extremity'),
('focus', 'Bones', 'RID28569', 'set of bone organs', 9, 'XXX'),
('focus', 'Acetabulum', 'RID2564', 'Acetabulum', 9, 'Lower extremity'),
('focus', 'Subclavian artery', 'RID773', 'Subclavian artery', 9, 'Chest'),
('focus', 'Parathyroid gland', 'RID7587', 'Parathyroid gland', 9, 'Neck'),
('focus', 'Nasopharynx', 'RID9990', 'Nasopharynx', 9, 'Neck'),
('focus', 'Pelvis veins', 'RID49971', 'Set of pelvis veins', 8, 'Pelvis'),
('focus', 'Cerebral artery', 'RID50283', 'Cerebral artery', 8, 'Head'),
('focus', 'Carotid artery.external', 'RID684', 'External carotid artery', 8, 'Neck'),
('focus', 'Appendix', 'RID168', 'Appendix', 8, 'Pelvis'),
('focus', 'AV fistula', 'RID4851', 'arteriovenous fistula', 8, 'XXX'),
('focus', 'Renal artery', 'RID936', 'Renal artery', 8, 'Abdomen'),
('focus', 'Extremity arteries', 'RID49963', 'Set of extremity arteries', 8, 'Extremity'),
('focus', 'Upper extremity vein', 'RID49983', 'Upper extremity vein', 8, 'Upper extremity'),
('focus', 'Extremity artery', 'RID49974', 'Extremity artery', 8, 'Extremity'),
('focus', 'Skull.base', 'RID28731', 'Base of cranium', 8, 'Head'),
('focus', 'Nasal bones', 'RID43410', 'Set of nasal bones', 7, 'Head'),
('focus', 'Abdominal veins', 'RID49957', 'Set of abdominal veins', 7, 'Abdomen'),
('focus', 'Lacrimal duct', 'RID28575', 'Lacrimal ducts', 7, 'Head'),
('focus', 'Lymphatic vessels', 'RID49640', 'Set of lymph vessels', 7, 'XXX'),
('focus', 'Pulmonary system', 'RID39189', 'respiratory system', 7, 'Chest'),
('focus', 'Hepatic artery', 'RID38078', 'hepatic artery', 7, 'Abdomen'),
('focus', 'Foot.sesamoid bones', 'RID35798', 'Sesamoid bone of foot', 7, 'Lower extremity'),
('focus', 'Spine.thoracolumbar junction', 'RID28739', 'Thoracolumbar junction', 6, 'Abdomen'),
('focus', 'Groin', 'RID476', 'inguinal part of abdomen', 6, 'Pelvis'),
('focus', 'Forefoot', 'RID2947', 'Forefoot', 6, 'Lower extremity'),
('focus', 'Cerebral cisterns', 'RID49538', 'set of cerebral cisterns', 6, 'Neck'),
('focus', 'Abdominal lymphatic vessels', 'RID31305', 'Set of abdominal lymphatic vessels', 6, 'Pelvis'),
('focus', 'Tissue', 'RID13298', 'portion of tissue', 6, 'XXX'),
('focus', 'Spine.lumbosacral junction', 'RID28734', 'Lumbosacral junction', 6, 'Pelvis'),
('focus', 'Circle of Willis', 'RID28600', 'Circle of Willis', 6, 'Neck'),
('focus', 'Pelvic lymphatic vessels', 'RID50274', 'set of pelvic lymphatic vessels', 6, 'Pelvis'),
('focus', 'Ribs.anterior', 'RID50168', 'anterior ends of ribs', 6, 'Chest'),
('focus', 'Ribs.posterior', 'RID28581', 'posterior ends of ribs', 6, 'Chest'),
('focus', 'Iliac vessels', 'RID49541', 'Set of iliac vessels', 6, 'Pelvis'),
('focus', 'Teeth', 'RID49873', 'set of teeth', 6, 'Head'),
('focus', 'Lumbosacral plexus', 'RID7456', 'Lumbosacral plexus', 5, 'Pelvis'),
('focus', 'Tendon', 'RID6067', 'tendon', 5, 'XXX'),
('focus', 'Pelvis bones', 'RID2527', 'Pelvic bone', 5, 'Pelvis'),
('focus', 'Brachial artery', 'RID865', 'brachial artery', 5, 'Upper extremity'),
('focus', 'Petrous part of temporal bone', 'RID9362', 'Petrous part of temporal bone', 5, 'Head'),
('focus', 'Optic foramen', 'RID43693', 'Optic foramen', 5, 'Head'),
('focus', 'Spinal artery', 'RID50273', 'Spinal artery', 5, 'XXX'),
('focus', 'Fallopian tubes', 'RID43579', 'Set of fallopian tubes', 5, 'Pelvis'),
('focus', 'Adrenal vein', 'RID34819', 'Adrenal vein', 5, 'Abdomen'),
('focus', 'Superior mesenteric vessels', 'RID49939', 'Set of superior mesenteric vessels', 5, 'Abdomen'),
('focus', 'Femoral vessels', 'RID49965', 'Set of femoral vessels', 5, 'Lower extremity'),
('focus', 'Foot vessels', 'RID49924', 'Set of foot vessels', 5, 'Lower extremity'),
('focus', 'Knee vessels', 'RID49927', 'Set of knee vessels', 5, 'Lower extremity'),
('focus', 'Shoulder vessels', 'RID49934', 'Set of shoulder vessels', 5, 'Upper extremity'),
('focus', 'Lower extremity arteries', 'RID50380', 'Set of lower extremity arteries', 5, 'Lower extremity'),
('focus', 'Tibioperoneal arteries', 'RID49636', 'set of tibio-peroneal arteries', 5, 'Lower extremity'),
('focus', 'Upper extremity vessel', 'RID49979', 'Upper extremity vessel', 5, 'Upper extremity'),
('focus', 'Peritoneal space', 'RID397', 'Peritoneal cavity', 5, 'Abdomen'),
('focus', 'Cerebral arteries', 'RID49534', 'Set of cerebral arteries', 5, 'Head'),
('focus', 'RO vessels', 'RID49864', 'Set of runoff vessels', 5, 'Lower extremity'),
('focus', 'Spine.lumbar vessels', 'RID49937', 'Set of lumbar spine vessels', 4, 'Abdomen'),
('focus', 'Spine.cervical vessels', 'RID49936', 'Set of cervical spine vessels', 4, 'Neck'),
('focus', 'Thigh.soft tissue', 'RID2660', 'Thigh', 4, 'Lower extremity'),
('focus', 'Cerebral vessels', 'RID50778', 'Cerebral vessels', 4, 'Head'),
('focus', 'Carotid artery.common', 'RID584', 'Common carotid artery', 4, 'Neck'),
('focus', 'Penis', 'RID362', 'penis', 4, 'Pelvis'),
('focus', 'Brachiocephalic artery', 'RID582', 'Brachiocephalic artery', 4, 'Chest'),
('focus', 'Thoracic inlet vessels', 'RID49941', 'Set of thoracic inlet vessels', 4, 'Chest'),
('focus', 'Joint space', 'RID41021', 'synovial cavity of joint', 4, 'XXX'),
('focus', 'Lower leg vessels', 'RID49929', 'Set of lower leg vessels', 4, 'Lower extremity'),
('focus', 'Popliteal space', 'RID2868', 'Popliteal fossa', 4, 'Lower extremity'),
('focus', 'Head artery', 'RID50267', 'Head artery', 4, 'Neck'),
('focus', 'Neck artery', 'RID50382', 'Neck artery', 4, 'Neck'),
('focus', 'Internal thoracic artery', 'RID823', 'internal thoracic artery', 4, 'Chest'),
('focus', 'Adrenal artery', 'RID935', 'Adrenal artery', 4, 'Abdomen'),
('focus', 'Visceral artery', 'RID50038', 'visceral artery', 4, 'Abdomen'),
('focus', 'Extremity lymphatic vessels', 'RID50275', 'Set of Extremity lymphatic vessels', 4, 'Extremity'),
('focus', 'Head veins', 'RID49968', 'Set of head veins', 4, 'Head'),
('focus', 'Toe', 'RID2992', 'Toe', 4, 'Lower extremity'),
('focus', 'Neck veins', 'RID49930', 'Set of neck veins', 4, 'Neck'),
('focus', 'Superior mesenteric artery', 'RID927', 'Superior mesenteric artery', 4, 'Abdomen'),
('focus', 'Brain.temporal', 'RID6392', 'Temporal brain region', 4, 'Head'),
('focus', 'Humerus.bicipital groove', 'RID1980', 'Bicipital groove of humerus', 4, 'Upper extremity'),
('focus', 'Upper extremity arteries', 'RID50381', 'Set of upper extremity arteries', 4, 'Upper extremity'),
('focus', 'Gastric artery', 'RID908', 'Left gastric artery', 4, 'Abdomen'),
('focus', 'Lung parenchyma', 'RID35739', 'Lung parenchyma', 4, 'Chest'),
('focus', 'Spine vessels', 'RID49935', 'Set of spine vessels', 4, 'XXX'),
('focus', 'Spine.thoracic vessels', 'RID49938', 'Set of thoracic spine vessels', 4, 'Chest'),
('focus', 'Eye', 'RID34550', 'Eye', 4, 'Head'),
('focus', 'Carotid artery.cervical', 'RID586', 'Cervical portion of internal carotid artery', 4, 'Neck'),
('focus', 'Submandibular gland', 'RID9968', 'Submandibular gland', 4, 'Head'),
('focus', 'Ribs.upper.posterior', 'RID50165', 'posterior ends of upper ribs', 4, 'Chest'),
('focus', 'Skeletal system.axial', 'RID49467', 'Axial skeleton', 4, 'Whole Body'),
('focus', 'Hand vessels', 'RID49966', 'Set of hand vessels', 4, 'Upper extremity'),
('focus', 'Skull base to mid-thigh', 'RID39570', 'skull base to mid-thigh', 4, 'Whole Body'),
('focus', 'Fallopian tube', 'RID295', 'uterine tube', 4, 'Pelvis'),
('focus', 'Penis vessels', 'RID49825', 'set of penis vessels', 3, 'Pelvis'),
('focus', 'Pericardial space', 'RID1408', 'Pericardial cavity', 3, 'Chest'),
('focus', 'Carotid artery.internal', 'RID585', 'Internal carotid artery', 3, 'Neck'),
('focus', 'Vertebral vessels', 'RID50280', 'set of vertebral vessels', 3, 'Neck'),
('focus', 'Femoral vein', 'RID1199', 'Femoral vein', 3, 'Lower extremity'),
('focus', 'Spine.thoracic epidural space', 'RID20051', 'Thoracic segment of spinal epidural space', 3, 'Chest'),
('focus', 'Pulmonary artery', 'RID974', 'Pulmonary artery', 3, 'Chest'),
('focus', 'Mesenteric artery', 'RID50284', 'Mesenteric artery', 3, 'Abdomen'),
('focus', 'Spine.thoracic intercostal nerve', 'RID22795', 'Intercostal nerve', 3, 'Chest'),
('focus', 'Intracranial vessel', 'RID50268', 'Intracranial vessel', 3, 'Head'),
('focus', 'Celiac artery', 'RID906', 'Celiac artery', 3, 'Abdomen'),
('focus', 'Celiac plexus', 'RID49533', 'celiac nerve plexus', 3, 'Abdomen'),
('focus', 'Diaphragm', 'RID1524', 'diaphragm', 3, 'Chest'),
('focus', 'Hypopharynx', 'RID10021', 'Hypopharynx', 3, 'Chest'),
('focus', 'Sinus tract', 'RID4843', 'Fistula', 3, 'XXX'),
('focus', 'Thigh vessels', 'RID49940', 'Set of thigh vessels', 3, 'Lower extremity'),
('focus', 'Spine.lumbar facet joint', 'RID7901', 'Facet joint of spine', 3, 'Abdomen'),
('focus', 'Orbit veins', 'RID50279', 'set of orbit veins', 3, 'Head'),
('focus', 'Maxilla', 'RID9236', 'Maxilla', 3, 'Head'),
('focus', 'Orbit vessels', 'RID49932', 'Set of orbit vessels', 3, 'Head'),
('focus', 'Inferior mesenteric artery', 'RID939', 'Inferior mesenteric artery', 3, 'Abdomen'),
('focus', 'Skeletal system', 'RID13208', 'Skeletal system', 3, 'Whole Body'),
('focus', 'Ribs.lower.posterior', 'RID50164', 'posterior ends of lower ribs', 3, 'Chest'),
('focus', 'Subphrenic space', 'RID399', 'Subphrenic space', 3, 'Abdomen'),
('focus', 'Skeletal system.peripheral', 'RID50049', 'Peripheral skeletal system', 3, 'Whole Body'),
('focus', 'Trachea', 'RID1247', 'trachea', 3, 'Chest'),
('focus', 'Spinal cord', 'RID7361', 'Spinal cord', 3, 'XXX'),
('focus', 'Intervertebral disc', 'RID7890', 'Intervertebral disk', 3, 'XXX'),
('focus', 'Mediastinum.superior', 'RID28742', 'Superior mediastinum', 3, 'Chest'),
('focus', 'Pedal lymphatic vessels', 'RID50384', 'Set of pedal lymphatic vessels', 3, 'Lower extremity'),
('focus', 'Spine vertebra', 'RID29154', 'Vertebra', 3, 'XXX'),
('focus', 'Foot.cuneiform bones', 'RID35744', 'Cuneiform bone', 3, 'Lower extremity'),
('focus', 'Trapezium', 'RID2193', 'Trapezium', 3, 'Upper extremity'),
('focus', 'Trapezoid', 'RID2195', 'Trapezoid', 3, 'Upper extremity'),
('focus', 'Wrist.scaphoid', 'RID2181', 'Scaphoid', 3, 'Upper extremity'),
('focus', 'Wrist.hamate', 'RID2198', 'Hamate', 3, 'Upper extremity'),
('focus', 'Triquetrum', 'RID2189', 'Triquetrum', 3, 'Upper extremity'),
('focus', 'Wrist.pisiform', 'RID2191', 'Pisiform', 3, 'Upper extremity'),
('focus', 'Seminal vesicle', 'RID357', 'seminal vesicle', 2, 'Pelvis'),
('focus', 'Shoulder.glenohumeral joint', 'RID1905', 'glenohumeral joint', 2, 'Upper extremity'),
('focus', 'Cerebral vein', 'RID34445', 'Cerebral vein', 2, 'Head'),
('focus', 'Anus', 'RID164', 'Anus', 2, 'Pelvis'),
('focus', 'AV shunt', 'RID4851', 'arteriovenous fistula', 2, 'XXX'),
('focus', 'Bones.long', 'RID34436', 'Long bone', 2, 'XXX'),
('focus', 'Peripheral veins', 'RID49964', 'Set of extremity veins', 2, 'XXX'),
('focus', 'Oropharynx', 'RID10003', 'Oropharynx', 2, 'Neck'),
('focus', 'Peripheral arteries', 'RID49963', 'Set of extremity arteries', 2, 'XXX'),
('focus', 'Spine.cervical.axis', 'RID7747', 'Axis', 2, 'Neck'),
('focus', 'Spine.cervical.odontoid', 'RID7749', 'Dens', 2, 'Neck'),
('focus', 'Splenic vein', 'RID1209', 'splenic vein', 2, 'Abdomen'),
('focus', 'Splenic artery', 'RID921', 'Splenic artery', 2, 'Abdomen'),
('focus', 'Renal arteries', 'RID49729', 'Set of renal arteries', 2, 'Abdomen'),
('focus', 'Peripheral artery', 'RID50272', 'Peripheral artery', 2, 'XXX'),
('focus', 'Spine.cervical facet joint', 'RID34563', 'cervical vertebral arch joint', 2, 'Neck'),
('focus', 'Spine.thoracic facet joint', 'RID7901', 'Facet joint of spine', 2, 'Chest'),
('focus', 'Pelvis arteries', 'RID50276', 'set of pelvic arteries', 2, 'Pelvis'),
('focus', 'Nerves.cranial', 'RID13190', 'Set of cranial nerves', 2, 'Head'),
('focus', 'Head arteries', 'RID49967', 'Set of head arteries', 2, 'Head'),
('focus', 'Epididymis', 'RID371', 'epididymis', 2, 'Pelvis'),
('focus', 'Olecranon', 'RID39681', 'Olecranon', 2, 'Upper extremity'),
('focus', 'Spine.cervical intervertebral disc', 'RID50392', 'Cervical intervertebral disk', 2, 'Neck'),
('focus', 'Ankle arteries', 'RID50379', 'Set of ankle arteries', 2, 'Lower extremity'),
('focus', 'Cerebral artery internal', 'RID35904', 'subdivision of cerebral part of internal carotid artery', 2, 'Head'),
('focus', 'Ribs.lower', 'RID50167', 'set of lower ribs', 2, 'Chest'),
('focus', 'Ribs.upper', 'RID50166', 'set of upper ribs', 2, 'Chest'),
('focus', 'Testicular vessels', 'RID50045', 'Set of testicular vessels', 2, 'Pelvis'),
('focus', 'Uterine artery', 'RID955', 'uterine artery', 2, 'Pelvis'),
('focus', 'Spine epidural space', 'RID7111', 'epidural space', 2, 'XXX'),
('focus', 'Subclavian vessels', 'RID50044', 'set of subclavian vessels', 2, 'Chest'),
('focus', 'Hepatic veins', 'RID50377', 'Set of hepatic veins', 2, 'Abdomen'),
('focus', 'Ribs.upper.anterior', 'RID28597', 'anterior ends of upper ribs', 2, 'Chest'),
('focus', 'Pharynx', 'RID13211', 'pharynx', 2, 'Neck'),
('focus', 'Iliac graft', 'RID50039', 'iliac artery graft', 2, 'Pelvis'),
('focus', 'Lower extremity vessel', 'RID49978', 'Lower extremity vessel', 2, 'Lower extremity'),
('focus', 'Thymus gland', 'RID1430', 'Thymus', 2, 'Chest'),
('focus', 'Wrist vessels', 'RID49945', 'Set of wrist vessels', 2, 'Upper extremity'),
('focus', 'Spine.cervicothoracic junction', 'RID28726', 'Cervicothoracic spine region', 2, 'Chest'),
('focus', 'Hepatic vein', 'RID1179', 'hepatic vein', 2, 'Abdomen'),
('focus', 'Peripheral nerve', 'RID7195', 'Peripheral nerve', 2, 'XXX'),
('focus', 'Spine.lumbar epidural space', 'RID20052', 'Lumbar segment of spinal epidural space', 2, 'Abdomen'),
('focus', 'Musculoskeletal tissue', 'RID13209', 'musculoskeletal system', 2, 'Extremity'),
('focus', 'Skull vertex to mid-thigh', 'RID50162', 'skull vertex to mid-thigh', 2, 'Whole Body'),
('focus', 'Internal jugular vein', 'RID1024', 'internal jugular vein', 2, 'Neck'),
('focus', 'Cervical arteries', 'RID49539', 'Set of cervical arteries', 2, 'Neck'),
('focus', 'Fistula', 'RID4843', 'Fistula', 2, 'XXX'),
('focus', 'Pulmonary veins', 'RID28588', 'Set of pulmonary veins', 2, 'Chest'),
('focus', 'Deep inferior epigastric artery', 'RID13091', 'Inferior epigastric artery', 2, 'Pelvis'),
('focus', 'Mesenteric vessels', 'RID50363', 'Set of mesenteric vessels', 2, 'Abdomen'),
('focus', 'Ileum', 'RID150', 'Ileum', 2, 'Abdomen'),
('focus', 'Perirenal space', 'RID434', 'Perirenal space', 2, 'Abdomen'),
('focus', 'Tendon or ligament', 'RID6067', 'tendon', 2, 'XXX'),
('focus', 'Foot.subtalar joint', 'RID3029', 'subtalar joint', 1, 'Lower extremity'),
('focus', 'Jugular vein', 'RID50727', 'neck vein', 1, 'Neck'),
('focus', 'Spine.thoracolumbar', 'RID35771', 'thoracolumbar vertebral column', 1, 'Abdomen'),
('focus', 'Mesenteric vein', 'RID50782', 'Mesenteric vein', 1, 'Abdomen'),
('focus', 'Right upper quadrant', 'RID29994', 'right upper quadrant of abdomen', 1, 'Abdomen'),
('focus', 'Stent', 'RID5598', 'Stent', 1, 'XXX'),
('focus', 'Biliary duct.common', 'RID199', 'Common bile duct', 1, 'Abdomen'),
('focus', 'Urinary bladder arteries', 'RID50277', 'st of urinary bladder arteries', 1, 'Pelvis'),
('focus', 'Carotid artery.extracranial', 'RID35846', 'subdivision of common carotid artery', 1, 'Neck'),
('focus', 'Carotid artery.intracranial', 'RID605', 'Cerebral part of internal carotid artery', 1, 'Head'),
('focus', 'Catheter', 'RID5576', 'Catheter', 1, 'XXX'),
('focus', 'Extracranial vessels', 'RID50287', 'Set of extracranial vessels', 1, 'XXX'),
('focus', 'Pancreatic artery', 'RID35951', 'Pancreatic artery', 1, 'Abdomen'),
('focus', 'Iliac artery.internal', 'RID945', 'Internal iliac artery', 1, 'Pelvis'),
('focus', 'Pylorus', 'RID122', 'Pylorus', 1, 'Abdomen'),
('focus', 'Shunt', 'RID5588', 'Shunt catheter', 1, 'XXX'),
('focus', 'Spine.lumbar space', 'RID7119', 'Subarachnoid space', 1, 'Abdomen'),
('focus', 'Three vessels', 'RID39545', 'Set of blood vessels', 1, 'XXX'),
('focus', 'Two vessels', 'RID39545', 'Set of blood vessels', 1, 'XXX'),
('focus', 'Abdominal arteries', 'RID50393', 'Set of abdominal arteries', 1, 'Abdomen'),
('focus', 'Intrahepatic portal system', 'RID38279', 'Intrahepatic branch of portal vein', 1, 'Abdomen'),
('focus', 'Renal vessel', 'RID50266', 'Renal vessel', 1, 'Abdomen'),
('focus', 'Epidural veins', 'RID1156', 'Epidural venous plexus', 1, 'XXX'),
('focus', 'Neck vessel', 'RID50383', 'Neck vessel', 1, 'Neck'),
('focus', 'Carotid vessels', 'RID49959', 'Set of carotid vessels', 1, 'Neck'),
('focus', 'Celiac vessels', 'RID49960', 'Set of celiac vessels', 1, 'Abdomen'),
('focus', 'Forearm vessels', 'RID49925', 'Set of forearm vessels', 1, 'Upper extremity'),
('focus', 'Symphysis pubis', 'RID2594', 'Symphysis pubis', 1, 'Pelvis'),
('focus', 'Tibioperoneal vessels', 'RID49942', 'Set of tibioperoneal vessels', 1, 'Lower extremity'),
('focus', 'Extremity vessel', 'RID50271', 'Extremity vessel', 1, 'Extremity'),
('focus', 'Femoral vessel', 'RID50269', 'Femoral vessel', 1, 'Lower extremity'),
('focus', 'Veins', 'RID28587', 'Set of veins', 1, 'XXX'),
('focus', 'Tributaries', 'RID49943', 'set of tributaries', 1, 'Lower extremity'),
('focus', 'Adrenal vessels', 'RID49958', 'Set of adrenal vessels', 1, 'Abdomen'),
('focus', 'Pulmonary vessels', 'RID49865', 'Set of pulmonary vessels', 1, 'Chest'),
('focus', 'Chest veins', 'RID49961', 'Set of chest veins', 1, 'Chest'),
('focus', 'Ankle vessels', 'RID49922', 'Set of ankle vessels', 1, 'Lower extremity'),
('focus', 'Brain stem', 'RID6677', 'Brainstem', 1, 'Head'),
('focus', 'Spinal veins', 'RID1155', 'Spinal vein', 1, 'XXX'),
('focus', 'Bronchial artery', 'RID880', 'Bronchial artery', 1, 'Chest'),
('focus', 'Gastroduodenal artery', 'RID910', 'Gastroduodenal artery', 1, 'Abdomen'),
('focus', 'Internal maxillary artery', 'RID734', 'Maxillary artery', 1, 'Head'),
('focus', 'Internal pudendal artery', 'RID954', 'Internal pudendal artery', 1, 'Pelvis'),
('focus', 'Azygos vein', 'RID1169', 'Azygos vein', 1, 'Abdomen'),
('focus', 'Intraosseous veins', 'RID50286', 'set of intraosseous veins', 1, 'XXX'),
('focus', 'Inferior mesenteric vein', 'RID1211', 'Inferior mesenteric vein', 1, 'Abdomen'),
('focus', 'Jejunum', 'RID148', 'Jejunum', 1, 'Abdomen'),
('focus', 'Peripheral vessels', 'RID49923', 'Set of extremity vessels', 1, 'XXX'),
('focus', 'Sinus vein', 'RID34474', 'Dural venous sinus', 1, 'Head'),
('focus', 'Subclavian vein', 'RID1013', 'Subclavian vein', 1, 'Chest'),
('focus', 'Superior mesenteric vein', 'RID1212', 'Superior mesenteric vein', 1, 'Abdomen'),
('focus', 'Visceral vessels', 'RID50378', 'Set of visceral vessels', 1, 'XXX'),
('focus', 'Chest wall', 'RID2468', 'Chest wall', 1, 'Chest'),
('focus', 'Spinal cavity', 'RID6135', 'Spinal canal', 1, 'XXX'),
('focus', 'Thoracic artery', 'RID50285', 'Thoracic artery', 1, 'Chest'),
('focus', 'Vas deferens', 'RID358', 'Vas deferens', 1, 'Pelvis'),
('focus', 'Genitourinary tract', 'RID43244', 'Genitourinary system', 1, 'Pelvis'),
('focus', 'Abdominal wall', 'RID30014', 'wall of abdomen', 1, 'Abdomen'),
('focus', 'Ovarian vessels', 'RID49970', 'Set of ovarian vessels', 1, 'Pelvis'),
('focus', 'Brain veins', 'RID49968', 'Set of head veins', 1, 'Head'),
('focus', 'Heart.ventricle', 'RID1392', 'Left ventricle', 1, 'Chest'),
('focus', 'Endomyocardium', 'RID50048', 'Endomyocardium', 1, 'Chest'),
('focus', 'Tube', 'RID5555', 'Tube', 1, 'XXX'),
('focus', 'Mesenteric arteries', 'RID50047', 'set of mesenteric arteries', 1, 'Abdomen'),
('focus', 'Breast vessels', 'RID50046', 'Set of breast vessels', 1, 'Breast'),
('focus', 'Popliteal vein', 'RID1201', 'Popliteal vein', 1, 'Lower extremity'),
('focus', 'Placenta', 'RID34557', 'placenta', 1, 'Pelvis'),
('focus', 'Vagina', 'RID325', 'Vagina', 1, 'Pelvis'),
('focus', 'Airway', 'RID1245', 'Airway', 1, 'Chest'),
('focus', 'Penis.soft tissue', 'RID362', 'penis', 1, 'Pelvis'),
('focus', 'Carpal tunnel', 'RID2314', 'Carpal tunnel', 1, 'Upper extremity'),
('focus', 'Pseudoaneurysm', 'RID3331', 'pseudoaneurysm', 1, 'Pelvis'),
('focus', 'Skull base to mid-thigh.bone', 'RID50173', 'set of bones from skull base to mid-thigh', 1, 'Whole Body'),
('focus', 'Kidney cortex', 'RID49727', 'cortex of kidney', 1, 'Abdomen'),
('focus', 'Oral tissue', 'RID50170', 'portion of oral tissue', 1, 'Head'),
('focus', 'Esophagus.cervical', 'RID31553', 'Cervical part of esophagus', 1, 'Neck'),
('focus', 'Visceral arteries', 'RID49542', 'Set of visceral arteries', 1, 'Abdomen'),
('focus', 'Spine.lumbar intercostal arteries', 'RID884', 'Intercostal artery', 1, 'Abdomen'),
('focus', 'Cerebral sinuses', 'RID49535', 'set of cerebral sinuses', 1, 'Head'),
('focus', 'Spine vessel', 'RID50281', 'Spinal vessel', 1, 'XXX'),
('focus', 'Adrenal vessel', 'RID50270', 'Adrenal vessel', 1, 'Abdomen'),
('focus', 'Aorta.abdominal.infrarenal', 'RID35944', 'Infrarenal aorta', 1, 'Abdomen'),
('focus', 'Joint.intermediate', 'RID39345', 'medium-sized joint', 1, 'XXX'),
('focus', 'Joint.major', 'RID39343', 'major joint', 1, 'XXX'),
('focus', 'Joint.small', 'RID39344', 'small joint', 1, 'XXX'),
('focus', 'Lower leg vessel', 'RID50342', 'Lower leg vessel', 1, 'Lower extremity'),
('focus', 'Lymphatic vessel', 'RID30383', 'Lymphatic vessel', 1, 'XXX'),
('focus', 'Nerve', 'RID13189', 'nerve', 1, 'XXX'),
('focus', 'Nerve root', 'RID18593', 'nerve root', 1, 'XXX'),
('focus', 'Hepatic vessels', 'RID50362', 'Set of hepatic vessels', 1, 'Abdomen'),
('focus', 'Aortic valve', 'RID1394', 'Aortic valve', 1, 'Chest'),
('focus', 'Teeth.maxilla', 'RID9279', 'Maxillary dental arcade', 1, 'Head'),
('focus', 'Teeth.mandible', 'RID9106', 'Mandibular dental arcade', 1, 'Head'),
('focus', 'Aortic root', 'RID482', 'Supraaortic valve area', 1, 'Chest'),
('focus', 'Spine.lumbar intervertebral disc', 'RID28830', 'Lumbar intervertebral disk', 1, 'Abdomen'),
('focus', 'Perirectal region', 'RID28680', 'Perirectal region', 1, 'Pelvis'),
('focus', 'Foot joint', 'RID3003', 'Joint of ankle or foot', 1, 'Lower extremity'),
('focus', 'Spine.cervical epidural space', 'RID20050', 'Cervical segment of spinal epidural space', 1, 'Chest'),
('focus', 'Sacrum epidural space', 'RID50528', 'Sacral segment of spinal epidural space', 1, 'Pelvis'),
('focus', 'Duodenum', 'RID134', 'duodenum', 1, 'Abdomen'),
('laterality', 'Unspecified', 'RID49843', 'Unspecified laterality', 1360, null),
('laterality', 'Right', 'RID5825', 'RIGHT', 1094, null),
('laterality', 'Left', 'RID5824', 'LEFT', 1078, null),
('laterality', 'Bilateral', 'RID5771', 'Bilateral', 836, null),
('laterality', 'Unilateral', 'RID38593', 'Unilateral', 45, null),
('aggregation', 'Views', 'RID49567', 'multiple views', 1968, null),
('aggregation', 'View', 'RID43399', '1 view', 827, null),
('aggregation', 'Views 2', 'RID43403', '2 views', 207, null),
('aggregation', 'Limited', 'RID5684', 'LIMITED', 182, null),
('aggregation', 'Views 3', 'RID43406', '3 views', 112, null),
('aggregation', 'Views GE 2', 'RID43402', '2 or more views', 85, null),
('aggregation', 'Views GE 3', 'RID43405', '3 or more views', 70, null),
('aggregation', 'Additional', 'RID49787', 'additional vessel same family', 56, null),
('aggregation', 'Perfusion', 'RID28948', 'Perfusion acquisition', 55, null),
('aggregation', 'Views 4', 'RID43408', '4 views', 54, null),
('aggregation', 'Views 1 or 2', 'RID43400', '1-2 views', 33, null),
('aggregation', 'Views GE 4', 'RID43407', '4 or more views', 28, null),
('aggregation', 'Views 5', 'RID43559', '5 views', 27, null),
('aggregation', 'Diagnostic', 'RID39446', 'diagnostic', 24, null),
('aggregation', 'Gated', 'RID10961', 'gated nuclear imaging acquisition', 23, null),
('aggregation', 'First pass', 'RID45658', 'first pass', 22, null),
('aggregation', 'Views 2 or 3', 'RID43401', '2-3 views', 20, null),
('aggregation', 'Wall motion', 'RID45640', 'wall motion', 18, null),
('aggregation', 'Ejection fraction', 'RID45645', 'ejection fraction', 17, null),
('aggregation', 'Multiple areas', 'RID49793', 'Multiple areas', 15, null),
('aggregation', 'Cine', 'RID10928', 'cine loop', 13, null),
('aggregation', 'Ventilation', 'RID45647', 'ventilation', 12, null),
('aggregation', 'Blood pool', 'RID45693', 'blood pool imaging', 10, null),
('aggregation', 'Views LE 3', 'RID43557', '3 or fewer views', 9, null),
('aggregation', 'Views 6', 'RID50157', '6 views', 9, null),
('aggregation', 'Uptake', 'RID49568', 'uptake', 9, null),
('aggregation', 'Views 3 or 4', 'RID46007', '3-4 views', 8, null),
('aggregation', 'Views GE 6', 'RID50161', '6 or more views', 8, null),
('aggregation', 'Dynamic', 'RID10385', 'Dynamic', 8, null),
('aggregation', 'Views 4 or 5', 'RID50174', '4-5 views', 7, null),
('aggregation', 'Views GE 5', 'RID50160', '5 or more views', 7, null),
('aggregation', 'Survey', 'RID28819', 'skeletal survey', 7, null),
('aggregation', 'Delayed', 'RID39065', 'Delayed', 7, null),
('aggregation', 'Quantitative', 'RID50375', 'Quantitative', 7, null),
('aggregation', 'Views 3 phase', 'RID43560', 'three phase imaging', 4, null),
('aggregation', 'Ventricular volume', 'RID50631', 'Ventricular volume', 4, null),
('aggregation', 'Qualitative', 'RID50374', 'Qualitative', 4, null),
('aggregation', '1 level', 'RID49781', '1 level', 4, null),
('aggregation', 'Views 7', 'RID50158', '7 views', 3, null),
('aggregation', 'Views 8', 'RID50159', '8 views', 3, null),
('aggregation', 'Post mortem', 'RID50541', 'Postmortem', 3, null),
('aggregation', 'Initial day', 'RID49575', 'initial day', 3, null),
('aggregation', '1 or 2', 'RID49658', '1-2 muscles', 2, null),
('aggregation', 'Brain death protocol', 'RID34681', 'brain death', 2, null),
('aggregation', 'Equilibrium', 'RID39065', 'Delayed', 2, null),
('aggregation', 'Complete', 'RID5689', 'complete', 2, null),
('aggregation', 'Additional day', 'RID49784', 'additional day', 2, null),
('aggregation', 'Additional level', 'RID36024', 'additional spinal level', 2, null),
('aggregation', 'Initial', 'RID49788', 'initial vessel', 2, null),
('aggregation', '2 levels', 'RID50537', '2 spinal levels', 2, null),
('aggregation', 'Serial', 'RID50636', 'Serial acquisition', 1, null),
('aggregation', 'Portable', 'RID10383', 'portable', 1, null),
('aggregation', 'Comparison', 'RID13169', 'Comparison image', 1, null),
('aggregation', '3 views', 'RID43406', '3 views', 1, null),
('aggregation', 'Views 2 phase', 'RID50539', 'Biphase', 1, null),
('aggregation', '3 phase', 'RID43560', 'three phase imaging', 1, null),
('aggregation', 'Single area', 'RID50540', 'Single area', 1, null),
('aggregation', 'Washout', 'RID34333', 'Washout delayed phase', 1, null),
('aggregation', 'Differential', 'RID50630', 'Regional differential', 1, null),
('aggregation', 'LE 4', 'RID43558', '4 or fewer views', 1, null),
('aggregation', 'Postoperative', 'RID5729', 'Postoperative', 1, null),
('aggregation', 'GE 4', 'RID43407', '4 or more views', 1, null),
('aggregation', 'LT 4', 'RID43557', '3 or fewer views', 1, null),
('aggregation', 'Multiple days', 'RID49574', 'multiple days', 1, null),
('aggregation', 'GE 1', 'RID50536', '1 or more views', 1, null),
('aggregation', 'GE 21', 'RID50331', 'greater than or equal to 21', 1, null),
('aggregation', 'Through ileal conduit', 'RID49735', 'through ilial conduit', 1, null),
('aggregation', 'Therapeutic', 'RID8', 'treatment', 1, null),
('aggregation', 'Secondary', 'RID49785', 'additional procedure', 1, null),
('aggregation', 'Final day', 'RID49576', 'final day', 1, null),
('aggregation', 'GE 3', 'RID43405', '3 or more views', 1, null),
('aggregation', 'GE 3 levels', 'RID50538', '3 or more spinal levels', 1, null);

-- trigram search index (pg_trgm assumed enabled by anatomy-v2-schema)
create index if not exists loinc_axis_name_trgm on public.loinc_axis using gin (part_name gin_trgm_ops);
create index if not exists loinc_axis_axis_idx on public.loinc_axis (axis);

-- read-only to everyone (reference data); no writes via API
alter table public.loinc_axis enable row level security;
drop policy if exists loinc_axis_read on public.loinc_axis;
create policy loinc_axis_read on public.loinc_axis for select using (true);

-- search RPC: ranked bilingual-agnostic match within an optional axis
create or replace function public.search_loinc_axis(p_q text, p_axis text default null, p_limit int default 20)
returns table(axis text, part_name text, radlex_rid text, preferred_name text, usage_count int, region_hint text, score real)
language sql stable as $$
  select l.axis, l.part_name, l.radlex_rid, l.preferred_name, l.usage_count, l.region_hint,
         greatest(similarity(l.part_name, p_q), similarity(coalesce(l.preferred_name,''), p_q)) as score
  from public.loinc_axis l
  where (p_axis is null or l.axis = p_axis)
    and (p_q is null or p_q = '' or l.part_name ilike '%'||p_q||'%' or coalesce(l.preferred_name,'') ilike '%'||p_q||'%'
         or similarity(l.part_name, p_q) > 0.2)
  order by score desc, l.usage_count desc
  limit greatest(1, least(p_limit, 100));
$$;
grant execute on function public.search_loinc_axis(text, text, int) to anon, authenticated;

do $$
declare n int; begin
  select count(*) into n from public.loinc_axis;
  raise notice 'loinc_axis rows: %', n;
end $$;
do $$ begin raise notice '✔ TASK: LOINC-BRIDGE-SCHEMA — completed'; end $$;
